# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calculator.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(417, 670)
        font = QtGui.QFont()
        font.setPointSize(24)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 100, 351, 81))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label.setFrameShape(QtWidgets.QFrame.Box)
        self.label.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label.setMidLineWidth(1)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(30, 210, 81, 71))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(120, 210, 81, 71))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(210, 210, 81, 71))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(300, 210, 81, 71))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(30, 290, 81, 71))
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_6.setGeometry(QtCore.QRect(210, 290, 81, 71))
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_7.setGeometry(QtCore.QRect(300, 290, 81, 71))
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_8.setGeometry(QtCore.QRect(120, 290, 81, 71))
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_9 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_9.setGeometry(QtCore.QRect(210, 370, 81, 71))
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_10 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_10.setGeometry(QtCore.QRect(30, 370, 81, 71))
        self.pushButton_10.setObjectName("pushButton_10")
        self.pushButton_11 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_11.setGeometry(QtCore.QRect(300, 370, 81, 71))
        self.pushButton_11.setObjectName("pushButton_11")
        self.pushButton_12 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_12.setGeometry(QtCore.QRect(120, 370, 81, 71))
        self.pushButton_12.setObjectName("pushButton_12")
        self.pushButton_13 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_13.setGeometry(QtCore.QRect(120, 450, 81, 71))
        self.pushButton_13.setObjectName("pushButton_13")
        self.pushButton_14 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_14.setGeometry(QtCore.QRect(210, 450, 81, 71))
        self.pushButton_14.setObjectName("pushButton_14")
        self.pushButton_15 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_15.setGeometry(QtCore.QRect(300, 450, 81, 71))
        self.pushButton_15.setObjectName("pushButton_15")
        self.pushButton_16 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_16.setGeometry(QtCore.QRect(30, 450, 81, 71))
        self.pushButton_16.setObjectName("pushButton_16")
        self.pushButton_17 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_17.setGeometry(QtCore.QRect(30, 530, 171, 71))
        self.pushButton_17.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_17.setObjectName("pushButton_17")
        self.pushButton_18 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_18.setGeometry(QtCore.QRect(300, 530, 81, 71))
        self.pushButton_18.setObjectName("pushButton_18")
        self.pushButton_19 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_19.setGeometry(QtCore.QRect(210, 530, 81, 71))
        self.pushButton_19.setObjectName("pushButton_19")
        
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        def numero_sete():
            texto = self.label.text()
            self.label.setText(texto+"7")
        def numero_oito():
            texto = self.label.text()
            self.label.setText(texto+"8")
        def numero_nove():
            texto = self.label.text()
            self.label.setText(texto+"9")
        def numero_quatro():
            texto = self.label.text()
            self.label.setText(texto+"4")
        def numero_cinco():
            texto = self.label.text()
            self.label.setText(texto+"5")
        def numero_seis():
            texto = self.label.text()
            self.label.setText(texto+"6")
        def numero_um():
            texto = self.label.text()
            self.label.setText(texto+"1")
        def numero_dois():
            texto = self.label.text()
            self.label.setText(texto+"2")
        def numero_tres():
            texto = self.label.text()
            self.label.setText(texto+"3")
        def numero_zero():
            texto = self.label.text()
            self.label.setText(texto+"0")

        def apagar_tudo():
            self.label.setText("")

        def somar():
            text = self.label.text()
            self.label.setText(text+"+")

        def equal():
            text = self.label.text()
            try:
                calc = eval(text)
                self.label.setText(str(calc))
            except:
                print("error")

        def vezes():
            text = self.label.text()
            self.label.setText(text+"*")

        def menos():
            text = self.label.text()
            self.label.setText(text+"-")
        def dividir():
            text = self.label.text()
            self.label.setText(text+"/")
            
        def remover():
            text = self.label.text()
            self.label.setText(text[:len(text)-1])


        self.pushButton_5.clicked.connect(numero_sete)
        self.pushButton_8.clicked.connect(numero_oito)
        self.pushButton_6.clicked.connect(numero_nove)
        self.pushButton_10.clicked.connect(numero_quatro)
        self.pushButton_12.clicked.connect(numero_cinco)
        self.pushButton_9.clicked.connect(numero_seis)
        self.pushButton_16.clicked.connect(numero_um)
        self.pushButton_13.clicked.connect(numero_dois)
        self.pushButton_14.clicked.connect(numero_tres)
        self.pushButton_17.clicked.connect(numero_zero)

        self.pushButton.clicked.connect(apagar_tudo)
        self.pushButton_15.clicked.connect(somar)
        self.pushButton_18.clicked.connect(equal)
        self.pushButton_7.clicked.connect(vezes)
        self.pushButton_11.clicked.connect(menos)
        self.pushButton_4.clicked.connect(dividir)
        self.pushButton_2.clicked.connect(remover)
              

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", ""))
        self.pushButton.setText(_translate("MainWindow", "AC"))
        self.pushButton_2.setText(_translate("MainWindow", "<<"))
        self.pushButton_3.setText(_translate("MainWindow", "%"))
        self.pushButton_4.setText(_translate("MainWindow", "/"))
        self.pushButton_5.setText(_translate("MainWindow", "7"))
        self.pushButton_6.setText(_translate("MainWindow", "9"))
        self.pushButton_7.setText(_translate("MainWindow", "X"))
        self.pushButton_8.setText(_translate("MainWindow", "8"))
        self.pushButton_9.setText(_translate("MainWindow", "6"))
        self.pushButton_10.setText(_translate("MainWindow", "4"))
        self.pushButton_11.setText(_translate("MainWindow", "-"))
        self.pushButton_12.setText(_translate("MainWindow", "5"))
        self.pushButton_13.setText(_translate("MainWindow", "2"))
        self.pushButton_14.setText(_translate("MainWindow", "3"))
        self.pushButton_15.setText(_translate("MainWindow", "+"))
        self.pushButton_16.setText(_translate("MainWindow", "1"))
        self.pushButton_17.setText(_translate("MainWindow", "0"))
        self.pushButton_18.setText(_translate("MainWindow", "="))
        self.pushButton_19.setText(_translate("MainWindow", ","))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
